# Generated by Django 5.0.6 on 2024-08-29 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="costomer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("phone_number", models.CharField(max_length=11)),
                ("walet", models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name="provider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("phone_number", models.CharField(max_length=11)),
                ("provider", models.BooleanField(default=False)),
            ],
        ),
    ]
