# Generated by Django 5.0.6 on 2024-08-29 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Internet_package", "0001_initial"),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now=True)),
                ("cost", models.IntegerField(blank=True, null=True)),
                (
                    "pakage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Internet_package.internet",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.costomer",
                    ),
                ),
            ],
        ),
    ]
